### PR TITLE
dec64 ported to C + several other improvements

### PR DESCRIPTION
**Pull request by vpisarev**
Hello,

thanks for the neat decimal engine! I'm thinking of adding something like that into my programming language (W.I.P), not as a substitution for hardware-accelerated float's, but as an option. Here is my little contribution:

* added C implementation: dec64.c, ported from dec64.asm (for now only supports clang & gcc; no MSVC yet, but should be more or less straightforward to add). *the proposed license for this implementation is MIT, to diverge from slightly fuzzy "public domain", but it can definitely be discussed*
* added C++ wrapper on top of C API with overloaded operators (also under MIT currently).
* added basic tests (converted from C tests) for the C++ API
* decorated dec64*.h with 'extern "C" {}'
* added CMake scripts to build it all
* run all the tests together (no failures on my machine)
* accelerated dec64_is_equal(), and also the slow branches of dec64_new(), dec64_add() & dec64_subtract()
* fixed bug in dec64_log()
* accelerated dec64_log() & dec64_exp() by 10x-100x, depending on the arguments ~~(but slightly less accurate, providing "just" ≈14.5 correct digits, according to the tests)~~. The accuracy is ≈15.5 digits.
* fixed multiple warnings from Clang in the tests
* made checks in the math tests slightly more liberal - use relative error instead of absolute
* added dec64_eps_equal(a, b, eps) to check abs(a - b) < eps
* added more convenient function to dump dec64 numbers, dec64_dump()
* added function to convert from double to dec64 and the corresponding `""_d` constructor for C++ (there can be some loss in accuracy, but the intention is to emulate "decimal" literals)

### CODE REVIEW

**Comment by douglascrockford** [comment]
This is great!

I would like to link to your DEC64 C++, rather than merge. I would then remove the obsolete C stuff from mine. Is that agreeable?

**Comment by vpisarev** [comment]
@douglascrockford, yes, this is fine. I've removed C++ wrapper for dec64

**Comment by douglascrockford** [comment]
Please give me the link to your C++ stuff. I will put the link in my repo and dec64.com and other places.

**Comment by vpisarev** [comment]
oh, I misunderstood you. You can put the link to https://github.com/vpisarev/DEC64/tree/alt.

**Comment by douglascrockford** [comment]
Thank you. Would you also like to take ownership of dec64_math.c?

**Comment by vpisarev** [comment]
@douglascrockford, thank you for the offer! :) I'm afraid, with OpenCV and the emerging programming language I'm working on, I will not have enough time for it. But you are welcome to take any parts of my fork of dec64.

**Pull request closed without merging**
