### PR TITLE
Update dec64.html

### PR DESCRIPTION
**Pull request by trustable-code**
Define text color to make text readable.
Screenshot: https://i.imgur.com/TbOliVR.png

### CODE REVIEW

**Comment by douglascrockford** [comment]
Where is the default color not black?

**Comment by trustable-code** [comment]
The introduction is show in the browser's default text color, because the CSS did not define the text color.
In my case, the default color is grey, which makes it hard to read.

**Comment by douglascrockford** [comment]
All of the browsers I tested with default to black. How do you get gray?

**Comment by trustable-code** [comment]
Change the default text color in the browser settings. Or use a dark theme under Linux and have the browser settings set to "use system colors".

**Comment by douglascrockford** [comment]
If someone chooses to screw up their browser, that's their business.

**Comment by douglascrockford** [comment]
Fix your browser.

**Pull request closed without merging**
